name: Development Terraform Apply

on:
  push:
    branches:
      - develop

jobs:
  preview:
    name: Apply
    environment:
      name: develop
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      ### Install tooling

      - name: Install Terramate
        uses: terramate-io/terramate-action@v1
          
      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install Terraform with asdf
        run: |
          asdf plugin add terraform
          asdf install terraform

      - name: List changed stacks
        id: list
        run: |
          echo "stdout<<STDOUT" >>$GITHUB_OUTPUT
          terramate list --changed >>$GITHUB_OUTPUT
          EXIT_CODE=$?
          echo "STDOUT" >>$GITHUB_OUTPUT
          exit ${EXIT_CODE}

      - name: Run Terraform init on changed stacks
        if: steps.list.outputs.stdout
        id: init
        run: |
          terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Create Terraform apply on changed stacks
        if: steps.list.outputs.stdout
        id: apply
        run: |
          terraform apply -input=false -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
