name: Stage Terraform Apply

on:
    push:
        branches:
        - stage

jobs:
  preview:
    name: Apply
    environment:
      name: stage
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Validate branch
        id: validate-branch
        run: |
          if [[ "${{ github.ref_name }}" != "stage" ]]; then
            echo "This workflow can only be triggered for the branch: stage"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: stage
          fetch-depth: 0

      ### Install tooling

      - name: Install Terramate
        uses: terramate-io/terramate-action@v1
          
      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install Terraform with asdf
        run: |
          asdf plugin add terraform
          asdf install terraform

      - name: List changed stacks
        id: list
        run: |
          echo "stdout<<STDOUT" >>$GITHUB_OUTPUT
          terramate list --changed >>$GITHUB_OUTPUT
          EXIT_CODE=$?
          echo "STDOUT" >>$GITHUB_OUTPUT
          exit ${EXIT_CODE}

      - name: Run Terraform init on changed stacks
        if: steps.list.outputs.stdout
        id: init
        run: |
          terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Create Terraform apply on changed stacks
        if: steps.list.outputs.stdout
        id: apply
        run: |
          terraform apply -input=false -auto-approve -var="version=${{ github.event.inputs.version }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}